name: Windows-RDP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Start Windows RDP with Pinggy
        shell: powershell
        run: |
          # 1. Enable RDP
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 0

          # 2. Setup runneradmin credentials
          cmd /c "net user runneradmin Tally@12345678 /add /y"
          cmd /c "net localgroup administrators runneradmin /add"

          # 3. Launch Pinggy TCP tunnel with visible output
          ssh -o StrictHostKeyChecking=no -p 443 -R0:localhost:3389 tcp@free.pinggy.io
